---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  annotations:
    configmanagement.gke.io/cluster-name: defaultcluster
    configmanagement.gke.io/source-path: config/cluster/clusterrole-secret-reader.yaml
    configsync.gke.io/declared-fields: '{"f:rules":{}}'
  labels:
    configsync.gke.io/declared-version: v1
  name: secret-reader
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
  - watch
  - list
