---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    configmanagement.gke.io/cluster-name: defaultcluster
    configmanagement.gke.io/source-path: config/cluster/crontab-crd.yaml
    configsync.gke.io/declared-fields: '{"f:spec":{"f:group":{},"f:names":{"f:kind":{},"f:plural":{},"f:shortNames":{},"f:singular":{}},"f:scope":{},"f:versions":{}}}'
  labels:
    configsync.gke.io/declared-version: v1
  name: crontabs.stable.example.com
spec:
  group: stable.example.com
  names:
    kind: CronTab
    plural: crontabs
    shortNames:
    - ct
    singular: crontab
  scope: Namespaced
  versions:
  - name: v1
    schema:
      openAPIV3Schema:
        properties:
          spec:
            properties:
              cronSpec:
                type: string
              image:
                type: string
              replicas:
                type: integer
            type: object
        type: object
    served: true
    storage: true
