kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: bob-rolebinding
subjects:
- kind: User
  name: bob@example.com
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: foo-admin
  apiGroup: rbac.authorization.k8s.io
