---
apiVersion: v1
kind: LimitRange
metadata:
  annotations:
    configmanagement.gke.io/cluster-name: defaultcluster
    configmanagement.gke.io/source-path: config/namespaces/limit-range.yaml
    configsync.gke.io/declared-fields: '{"f:spec":{"f:limits":{}}}'
  labels:
    configsync.gke.io/declared-version: v1
  name: limits
  namespace: team-2
spec:
  limits:
  - max:
      cpu: 300m
      memory: 1Gi
    type: Container
  - max:
      storage: 2Gi
    type: PersistentVolumeClaim
