---
apiVersion: v1
kind: ResourceQuota
metadata:
  annotations:
    configmanagement.gke.io/cluster-name: defaultcluster
    configmanagement.gke.io/source-path: config/namespaces/team-2/resource-quota-pvc.yaml
    configsync.gke.io/declared-fields: '{"f:spec":{"f:hard":{"f:persistentvolumeclaims":{}}}}'
  labels:
    configsync.gke.io/declared-version: v1
  name: pvc
  namespace: team-2
spec:
  hard:
    persistentvolumeclaims: "6"
