# deny all ingress traffic to avoid Pods from one namespace
# accidentally sending traffic to Services in other namespaces.
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: deny-all
spec:
  podSelector:
    matchLabels:

  ingress:
  - from:
    - podSelector: {}

