---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  annotations:
    configmanagement.gke.io/cluster-name: defaultcluster
    configmanagement.gke.io/source-path: config/namespaces/rnd/incubator-1/incubator-1-admin-role.yaml
    configsync.gke.io/declared-fields: '{"f:rules":{}}'
  labels:
    configsync.gke.io/declared-version: v1
  name: incubator-1-admin
  namespace: incubator-1
rules:
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - '*'
- apiGroups:
  - ""
  resources:
  - namespaces
  verbs:
  - get
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - roles
  - rolebindings
  verbs:
  - get
  - list
