apiVersion: v1
kind: Namespace
metadata:
  creationTimestamp: null
  name: busybox
---
apiVersion: v1
kind: Pod
metadata:
  name: busybox
  namespace: busybox
  labels:
    app: busybox
spec:
  containers:
  - image: busybox
    command:
      - sleep
      - "3600"
    imagePullPolicy: IfNotPresent
    name: busybox
  restartPolicy: Always
---
apiVersion: v1
kind: Pod
metadata:
  name: busybox1
  namespace: busybox
  labels:
    app: busybox1
spec:
  containers:
  - image: busybox
    command:
      - sleep
      - "3600"
    imagePullPolicy: IfNotPresent
    name: busybox
  restartPolicy: Always
