apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: tenant-admin
  namespace: tenant-a
  annotations:
    client.lifecycle.config.k8s.io/mutation: ignore
    foo: bar
    foofoo: bar
rules:
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - '*'
