---
apiVersion: v1
kind: ResourceQuota
metadata:
  annotations:
    configmanagement.gke.io/cluster-name: defaultcluster
    configmanagement.gke.io/namespace-selector: analytics-selector
    configmanagement.gke.io/source-path: config/namespaces/eng/quota.yaml
    configsync.gke.io/declared-fields: '{"f:metadata":{"f:annotations":{"f:configmanagement.gke.io/namespace-selector":{}}},"f:spec":{"f:hard":{"f:cpu":{},"f:memory":{},"f:pods":{}}}}'
  labels:
    configsync.gke.io/declared-version: v1
  name: quota
  namespace: analytics
spec:
  hard:
    cpu: 100m
    memory: 100Mi
    pods: "1"
