apiVersion: configmanagement.gke.io/v1
kind: ConfigManagement
metadata:
  name: config-management
  namespace: config-management-system
spec:
  clusterName: belgium
  git:
    syncRepo: git@github.com:<GITHUB-USERNAME>/anthos-config-management-samples.git
    syncBranch: 1.0.0
    secretType: ssh
    policyDir: "docs/locality-specific-policy/"
